import os
import sys
import glob
import sipconfig 

module  = 'ifs'
sipfile = 'sip/ifs.sip'
output  = 'sip/generated'
# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "%s/%s.sbf"%(output,module)

# Get the SIP configuration information.
config = sipconfig.Configuration()

# compiler sip
cmd = " ".join([config.sip_bin, "-c", output, sipfile])
if(0 != os.system(cmd)):
  print(cmd, 'failed')

# Run SIP to generate the code.
cmd = " ".join([config.sip_bin, "-c", output, "-b", build_file, sipfile])
if(0 != os.system(cmd)):
  print(cmd, 'failed')

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)
# Generate the Makefile itself.
makefile.generate()
    
